import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "react-confirm-alert/src/react-confirm-alert.css";
import { ThemeProvider } from "./context/ThemeContext";
import { AuthProvider } from "./context/AuthContext";
import { ToastContainer } from "react-toastify";
import { DataCountsProvider } from "./context/DataCountsContext";
import { RepairRequestsProvider } from "./context/RepairRequestsContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "EVOFIX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
        <AuthProvider>
          <RepairRequestsProvider>
            <DataCountsProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </DataCountsProvider>
          </RepairRequestsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
